special_map = {
    "bar symbol": "|",
    "minus": "-",
    "tilde": "~",
    "clamor": "!",
    "questo": "?",
    "(caret|carrot)": "^",
    "(dot|period)": ".",
    "committee": ",",
    "boom": ", ",
    "backslash": "\\",
    "underscore": "_",
    "starling": "*",
    "(deckle|pointy)": ":",
    "semper": ";",
    "at sign": "@",
    "[double] quote": '"',
    "single quote": "'",
    "hashtag": "#",
    "Dolly": "$",
    "modulo": "%",
    "ampersand": "&",
    "slash": "/",
    "equals": "=",
    "plus": "+",
    "ace": " ",
    "backtick": "`",
}

letter_map = {
    "arch": "a",
    "brov": "b",
    "char": "c",
    "delta": "d",
    "echo": "e",
    "foxy": "f",
    "goof": "g",
    "hotel": "h",
    "india": "i",
    "julia": "j",
    "kilo": "k",
    "Lima": "l",
    "mike": "m",
    "Novakeen": "n",
    "oscar": "o",
    "prime": "p",
    "quebec": "q",
    "romeo": "r",
    "sierra": "s",
    "tango": "t",
    "uniform": "u",
    "victor": "v",
    "whiskey": "w",
    "`x-ray`": "x",
    "yankee": "y",
    "zulu": "z",
}

digit_map = {
    "zero": "0",
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
}

format_list = [
    "(sentence|sense|since) case",
    "camel case",
    "pass case",
    "snake case",
    "uppercase",
    "lowercase",
    "squash",
    "lowercase squash",
    "uppercase squash",
    "squash lowercase",
    "squash uppercase",
    "dashify",
    "lowercase dashify",
    "uppercase dashify",
    "dashify lowercase",
    "dashify uppercase",
    "dotify",
    "lowercase dotify",
    "uppercase dotify",
    "dotify lowercase",
    "dotify uppercase",
    "say",
    "environment variable",
]
